# Generated by Django 3.2.4 on 2021-07-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210622_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_libro',
            name='id_categoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria'),
        ),
        migrations.AlterField(
            model_name='categoria_libro',
            name='nombre_categoria',
            field=models.CharField(max_length=50, verbose_name='Nombre de categoria'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor_libro',
            field=models.CharField(max_length=50, verbose_name='Autor del libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion_libro',
            field=models.CharField(max_length=50, verbose_name='Descripcion del libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_libro',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre_libro',
            field=models.CharField(max_length=50, verbose_name='Nombre del libro'),
        ),
    ]
